import { Inter } from 'next/font/google'

import ToastContext from './context/ToastContext'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Messanger Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContext />
        {children}
        </body>
    </html>
  )
}
